sudo: required
services:
    - docker

before_install:
    - docker build -t junaid388/docker-react -f Dockerfile.dev .

script:
    - docker run junaid388/docker-react npm run test -- --coverage

deploy:
    provider: pages #github pages
    skip_cleanup: true
    keep_history: true
    on:
        branch: master